export type ExchangeType = {

	id: number,
	valid: number,
	serialId: string,
	userId: number,
	status: number,
	points: number,
	addressId: number,
	addressProvince: string,
	addressCity: string,
	addressDistrict: string,
	addressDetail: string,
	addressRoom: string,
	contactName: string,
	contactPhone: string,
	createTime: string,
	createUser: string,
	modifyTime: string,
	modifyUser: string,
	productId: number,
	productCoverImgUrl: string,
	productName: string,

}
