export default defineAppConfig({
	pages: [
		'view/page/tab/tab-page',
		'view/page/single/search/search-page',
		'view/page/single/rich-text/rich-text-page',
		'view/page/single/server-me/server-me-page',
		'view/page/single/user-info/user-info-page',
		'view/page/single/points-mall/points-mall-page',
		'view/page/single/address-management/address-management-page',
		'view/page/single/address-input/address-input-page',
		'view/page/single/point-history/point-history-page',
		'view/page/single/exchange-history/exchange-history-page',
		'view/page/single/goods-detail/goods-detail-page',
		'view/page/single/goods-billing-address/goods-billing-address-page',
		'view/page/single/order-center-user/order-center-user-page',
		'view/page/single/order-detail-user/order-detail-user-page',
		'view/page/single/order-center-server/order-center-server-page',
		'view/page/single/order-detail-server/order-detail-server-page',
		'view/page/single/coupon-list/coupon-list-page',
		'view/page/single/member-center/member-center-page',
		'view/page/single/comment-input/comment-input-page',
		'view/page/single/housekeeping-detail/housekeeping-detail-page',
		'view/page/single/housekeeping-billing/housekeeping-billing-page',
		'view/page/single/housekeeping-address-selector/housekeeping-address-selector-page',
		'view/page/single/housekeeping-time-selector/housekeeping-time-selector-page',
		'view/page/single/housekeeping-housekeeper-selector/housekeeping-housekeeper-selector-page',
		'view/page/single/housekeeping-coupon-selector/housekeeping-coupon-selector-page',
		'view/page/single/housekeeper-comment/housekeeper-comment-page',
	],
	window: {
		backgroundTextStyle: 'light',
		navigationBarBackgroundColor: '#fff',
		navigationBarTitleText: 'WeChat',
		navigationBarTextStyle: 'black',
	},
	requiredPrivateInfos: [
		'chooseLocation',
	],
});
